name: Flutter Linux Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x' # Use a specific Flutter version or 'stable'

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Install GTK development files
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev

      - name: Enable Linux desktop
        run: flutter config --enable-linux-desktop

      - name: Build Linux App
        run: flutter build linux --release

      - name: Upload Linux App artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-app
          path: build/linux/x64/release/bundle
