name: Flutter macOS Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x' # Use a specific Flutter version or 'stable'

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Build macOS App
        run: flutter build macos --release

      - name: Upload macOS App artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-app
          path: build/macos/Build/Products/Release/Runner.app
