name: Flutter Web Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x' # Use a specific Flutter version or 'stable'

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Build Web App
        run: flutter build web --release

      - name: Upload Web App artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-app
          path: build/web
